name: x_hwindi
description: X-Hwindi
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  curl_logger_dio_interceptor: ^1.0.0
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_geocoding:
    git:
      url: https://github.com/iamngoni/google_geocoding.git
  google_maps_flutter: ^2.5.0
  handy_extensions: ^0.1.6
  image_picker: ^1.0.4
  injectable: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  jwt_decode: ^0.3.1
  localregex: ^4.0.5
  lottie: ^2.7.0
  modal_bottom_sheet: ^3.0.0-pre
  network_info_plus: ^4.0.2
  path: ^1.8.0
  path_provider:
  permission_handler:
  pinput: ^3.0.1
  pretty_dio_logger: ^1.3.1
  relative_scale: ^2.0.0
  replay_bloc: ^0.2.4
  sentry_dio: ^7.10.1
  sentry_flutter: ^7.10.1
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner:
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator:
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: 'Inter'
      fonts:
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Black.ttf
          weight: 900